// packages/react/src/AgiTerminal.tsx
import { useRef, useEffect, useImperativeHandle, forwardRef } from "react";
import { AgiRenderedTerminal } from "@work-with-ai/sdk";

export interface AgiTerminalProps {
  /** agisdk-server base URL */
  endpoint: string;
  /** API key */
  apiKey?: string;
  /** Logto access token (JWT); takes precedence over apiKey */
  accessToken?: string;
  /** Session ID (from REST API createSession) */
  sessionId?: string;
  /** Theme — preset name or custom theme object */
  theme?: "dark" | "light" | Record<string, string>;
  /** Font size */
  fontSize?: number;
  /** Font family */
  fontFamily?: string;
  /** Cursor style */
  cursorStyle?: "block" | "underline" | "bar";
  /** Enable WebGL renderer */
  webgl?: boolean;
  /** Container class name */
  className?: string;
  /** Container style */
  style?: React.CSSProperties;
  /** PTY output callback */
  onOutput?: (data: Uint8Array) => void;
  /** WebSocket connected */
  onConnect?: () => void;
  /** WebSocket disconnected */
  onDisconnect?: () => void;
}

export interface AgiTerminalHandle {
  focus: () => void;
  fit: () => void;
  write: (data: string | Uint8Array) => void;
}

export const AgiTerminal = forwardRef<AgiTerminalHandle, AgiTerminalProps>(
  function AgiTerminal(
    {
      endpoint,
      apiKey,
      accessToken,
      sessionId,
      theme = "dark",
      fontSize,
      fontFamily,
      cursorStyle,
      webgl,
      className,
      style,
      onOutput,
      onConnect,
      onDisconnect,
    },
    ref,
  ) {
    const containerRef = useRef<HTMLDivElement>(null);
    const terminalRef = useRef<AgiRenderedTerminal | null>(null);

    // Create / recreate terminal on connection-level prop changes
    useEffect(() => {
      if (!containerRef.current) return;

      terminalRef.current = new AgiRenderedTerminal({
        container: containerRef.current,
        endpoint,
        apiKey,
        accessToken,
        sessionId,
        theme,
        fontSize,
        fontFamily,
        cursorStyle,
        webgl,
        onOutput,
        onConnect,
        onDisconnect,
      });

      return () => {
        terminalRef.current?.dispose();
        terminalRef.current = null;
      };
    }, [endpoint, apiKey, accessToken, sessionId]);

    // Watch theme changes
    useEffect(() => {
      if (terminalRef.current && theme) {
        terminalRef.current.setTheme(theme);
      }
    }, [theme]);

    // Watch fontSize changes
    useEffect(() => {
      if (terminalRef.current && fontSize) {
        terminalRef.current.terminal.options.fontSize = fontSize;
        terminalRef.current.fit();
      }
    }, [fontSize]);

    // Expose imperative API via ref
    useImperativeHandle(ref, () => ({
      focus: () => terminalRef.current?.focus(),
      fit: () => terminalRef.current?.fit(),
      write: (data: string | Uint8Array) => terminalRef.current?.write(data),
    }));

    return (
      <div
        ref={containerRef}
        className={className}
        style={{ width: "100%", height: "100%", ...style }}
      />
    );
  },
);

// packages/angular/src/agi-terminal.component.ts
import {
  Component,
  ElementRef,
  Input,
  Output,
  EventEmitter,
  ViewChild,
  AfterViewInit,
  OnChanges,
  OnDestroy,
  SimpleChanges,
} from "@angular/core";
import { AgiRenderedTerminal } from "@work-with-ai/sdk";

@Component({
  selector: "agi-terminal",
  standalone: true,
  template: `<div #terminalContainer style="width:100%;height:100%"></div>`,
})
export class AgiTerminalComponent
  implements AfterViewInit, OnChanges, OnDestroy
{
  @ViewChild("terminalContainer") containerRef!: ElementRef<HTMLDivElement>;

  @Input({ required: true }) endpoint!: string;
  @Input() apiKey?: string;
  /** Logto access token (JWT); takes precedence over apiKey */
  @Input() accessToken?: string;
  @Input() sessionId?: string;
  @Input() theme: "dark" | "light" | Record<string, string> = "dark";
  @Input() fontSize?: number;
  @Input() fontFamily?: string;
  @Input() cursorStyle?: "block" | "underline" | "bar";
  @Input() webgl: boolean = true;

  @Output() output = new EventEmitter<Uint8Array>();
  @Output() connected = new EventEmitter<void>();
  @Output() disconnected = new EventEmitter<void>();

  private terminal: AgiRenderedTerminal | null = null;

  ngAfterViewInit(): void {
    this.terminal = new AgiRenderedTerminal({
      container: this.containerRef.nativeElement,
      endpoint: this.endpoint,
      apiKey: this.apiKey,
      accessToken: this.accessToken,
      sessionId: this.sessionId,
      theme: this.theme,
      fontSize: this.fontSize,
      fontFamily: this.fontFamily,
      cursorStyle: this.cursorStyle,
      webgl: this.webgl,
      onOutput: (data) => this.output.emit(data),
      onConnect: () => this.connected.emit(),
      onDisconnect: () => this.disconnected.emit(),
    });
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (!this.terminal) return;

    if (changes["theme"] && !changes["theme"].firstChange) {
      this.terminal.setTheme(this.theme);
    }

    if (changes["fontSize"] && !changes["fontSize"].firstChange) {
      if (this.fontSize) {
        this.terminal.terminal.options.fontSize = this.fontSize;
        this.terminal.fit();
      }
    }
  }

  ngOnDestroy(): void {
    this.terminal?.dispose();
    this.terminal = null;
  }

  focus(): void {
    this.terminal?.focus();
  }

  fit(): void {
    this.terminal?.fit();
  }

  write(data: string | Uint8Array): void {
    this.terminal?.write(data);
  }
}
